---

- name: Configure and install apache2 web server
  hosts: all
  become: true

  tasks:
    - name: Install apache2
      apt:
        - name: apache2
          state: present
          update_cache: true

    - name: Starting and enabling apache2 on start
      service:
        - name: apache2
          state: started
          enabled: true

    - name: Copying index.html to apache2
      copy:
        src: index.html
        dest: /var/www/html/index.html 
